server:
  port: 8002

spring:
  application:
    name: spring-cloud-provider01
  datasource:
    url: jdbc:mysql://47.240.95.83:3360/springclouddemo?nullCatalogMeansCurrent=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: myself
    password: wang@123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:static/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.wjf.springcloud.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/