server:
  port: 8002
spring:
  application:
    name: spring-cloud-consumer01

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/