server:
  port: 8850
spring:
  application:
    name: spring-cloud-hystrix-consumer01
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    #连接池最大连接数，默认200
    max-connections: 500
    #每一个IP最大占用多少连接 默认 50
    max-connections-per-route: 50
    #默认连接超时时间：2000毫秒
    connection-timeout: 8000
    #连接池管理定时器执行频率：默认 3000毫秒
    connection-timer-repeat: 6000
    #连接池中存活时间，默认为5
    time-to-live: 5
    time-to-live-unit: minutes

#ribbon:
#  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
#  ReadTimeout: 7000   #负载均衡超时时间，默认值5000
#  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
#  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
#  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
#  http:
#    client:
#      enabled: true
ribbon:
  httpclient:
    enabled: true
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
  ConnectTimeout: 60000
  ReadTimeout: 60000