server:
  port: 8003

spring:
  application:
    name: zookeeper-provider
  datasource:
    url: jdbc:mysql://47.240.95.83:3360/springclouddemo?nullCatalogMeansCurrent=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: myself
    password: wang@123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: 192.168.214.130:2181