server:
  port: 8850
spring:
  application:
    name: spring-cloud-hystrix-consumer01
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    #连接池最大连接数，默认200
    max-connections: 500
    #每一个IP最大占用多少连接 默认 50
    max-connections-per-route: 50
    #默认连接超时时间：2000毫秒
    connection-timeout: 8000
    #连接池管理定时器执行频率：默认 3000毫秒
    connection-timer-repeat: 6000
    #连接池中存活时间，默认为5
    time-to-live: 5
    time-to-live-unit: minutes

ribbon:
  httpclient:
    enabled: true
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
  ConnectTimeout: 60000
  ReadTimeout: 60000  